name: Integración continùa
on: push
jobs:
    compilar-y-ejecutar:
        runs-on: ubuntu-latest
        steps:
            - name: clonar el repositorio
              uses: actions/checkout@v4
            - name: compilar codigo
              run: gcc hola.c -o hola

